<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <!-- Тестам разрешены подчёркивания в именах методов -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Tropa.Core\Tropa.Core.csproj" />
    <ProjectReference Include="..\..\src\Tropa.Infrastructure\Tropa.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Tropa.Service\Tropa.Service.csproj" />
  </ItemGroup>
</Project>
